#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X

# bspc monitor -d I

bspc config border_width         1
bspc config window_gap           10
bspc config top_padding          0
bspc config left_padding         0
bspc config right_padding        0
bspc config buttom_padding       0

bspc config active_border_color "#458588"
bspc config focused_border_color "#458588"
# 83A598
bspc config normal_border_color "#928374"
bspc config urgent_border_color "#B16286"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a LibreWolf state=floating follow=on
bspc rule -a Pcmanfm state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr
exec /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
picom -b --config ~/.config/picom/picom.conf &
feh --bg-scale ~/Pictures/wallhaven-83gmpk.jpg &
dunst &
polybar &
